### ISSUE TITLE
ModuleNotFoundError: No module named 'openai'

### ISSUE THREAD

**Issue by nirvana7777** [samay825/W0rm-Gpt#13]
Hi there !

I've followed the steps, everything in requirements.txt is installed but when I run

sudo python3 main.py 

* I get the "error: externally-managed-environment" & 
* it also says "ModuleNotFoundError: No module named 'openai'" (I checked on my pc & openai is installed)

Thank you for helping !

**Comment by samay825** [comment]
i have updated , reclone again ...

**Comment by nirvana7777** [comment]
Hi

Now it gives

"

raceback (most recent call last):
  File "/home/nessh777/W0rm-Gpt/main.py", line 1, in <module>
    import main
  File "/home/nessh777/W0rm-Gpt/main.py", line 2, in <module>
    main.Xyz()
    ^^^^^^^^


"

**Comment by nirvana7777** [comment]
*Traceback
