### ISSUE TITLE
Launch time error shows

### ISSUE THREAD

**Issue by Laddi-47** [samay825/W0rm-Gpt#14]
Good morning sir!
Jab mai W0rm-Gpt ko launch krta hu to errors aa rhe hai aur error ye aa raha hai dekhna 
'Traceback (most recent call last):
  File "/data/data/com.termux/files/home/W0rm-Gpt/main.py", line 1, in <module>
    import main
ImportError: dlopen failed: "/data/data/com.termux/files/home/W0rm-Gpt/main.cpython-311.so" is 64-bit instead of 32-bit'Please sir help me how i can fix it sir response me 
![Error](https://github.com/samay825/W0rm-Gpt/assets/166978600/39acb945-c2c7-42fc-80de-0ec73e2ef544)

**Comment by samay825** [comment]
Please use other device ... Because this script works only in 64 bit architecture phones
