### ISSUE TITLE
how to work with him ?

### ISSUE THREAD

**Issue by profesionalleet1337** [samay825/W0rm-Gpt#2]
I tried set up, but if I need to work with him, and ask question's from where I should take the API key , its push me to the original site, If I have registration there in the chatgpt, I don't want to mess with him, if I don't have an account , from where I should take the API ?

**Comment by samay825** [comment]
Generally making account is very easy and I think every person can make f@ke account 
I think this hint is good for you 
Love and peace ✌️🕊️

**Comment by profesionalleet1337** [comment]
> Generally making account is very easy and I think every person can make f@ke account I think this hint is good for you Love and peace ✌️🕊️

Does it make everything, that I need /want ? For example, If i want from him , to gave me the code for creating phishing page, does the bot will generate for me working one ? I mean, yeah, everybody can make a fake account, but I need to make fake gmail, to buy virtual phone and so on.. You know, so before I do it, I want tot know, does it worthy ? And actually what the this GPT could make - everything ?
