### ISSUE TITLE
the working prompt

### ISSUE THREAD

**Issue by maciejopalinski** [samay825/W0rm-Gpt#9]
I am sorry zork i can't understand your script and all .. i know you are updating the script .. I am mad and fellow

**Comment by samay825** [comment]
Yes bruh I know you are fellow don't worry ❤️

**Comment by maciejopalinski** [comment]
Why did you edit out my comment?

**Comment by maciejopalinski** [comment]
You know that everyone can see the edit history? 🤣🤣🤣

**Comment by maciejopalinski** [comment]
You are a scammer
